### ISSUE TITLE
Add readthedocs link to project (and perhaps readme.rst)

### ISSUE THREAD

**Issue by WoLpH** [ssokolow/fastdupes#26]
Having a clickable link to the readthedocs page from the readme and perhaps as project homepage would make things easier :)

Also, awesome project... I've been pondering to write something similar since I've been looking for something like this for so long.

Just a note, to make installing it easier I've added it to Pypi, let me know which username I should transfer the ownership too (if you're interested in that): https://pypi.python.org/pypi/fastdupes

Another addition to the docs, install now as easy as: `pip install fastdupes`

**Comment by ssokolow** [comment]
Hi. Sorry about that. Fastdupes is one of the projects where I was working hard to modernize it and hit a time-crunch brick wall.

There actually *is* a clickable link to the docs but you're right that the [docs: latest] badge isn't exactly obvious so I'll add a more visible one once I finish working through my morning e-mails. I've already added it as the web page since that was just a couple of clicks.

As for PyPI, I'll need to create an account first. I was sort of planning to wait until I'd written a comprehensive unit test suite so I could set up continuous deployment via Travis-CI.

(The idea behind continuous deployment is that, whenever you think of some pre-release testing you'd normally do manually, you write it as an automated test. Then, you can trust that the test server will be at least as thorough as you and you can automate the process of making releases.)

**Comment by WoLpH** [comment]
Having some automated tests is indeed nice, add Travis to the mix and you'll automatically get test status for every pull request on github, really handy :)

I can definitely imagine the time-crunch, I have the same with many of my projects... takes a lot of time to maintain projects. Regardless, you've done a great job here, very nice project :)

**Comment by ssokolow** [comment]
No need to tell me. Here's the current early draft of the policy I eventually want to retrofit all my projects to follow.

![2015-04-04-125140_1280x1002_scrot](https://cloud.githubusercontent.com/assets/46915/6993731/5a579364-dacc-11e4-8a16-601ad7e04516.png)

**Comment by WoLpH** [comment]
Very nice, a few new projects/sites for me as well which I'll take a look at. Thanks!

**Comment by ssokolow** [comment]
Glad I could help. I should probably clarify that, when multiple things in the same field are bolded, that means that they should be used in concert.

For example, both Travis and Appveyor are bolded because Travis-CI only does builds on Linux (or OSX if you lie in your config and claim to be an Objective-C project... took me a while to figure out what they were using their OSX boxes for) while Appveyor offers a Windows-only version of the same functionality. Using them together lets you test and do automated builds for both Linux and Windows.

**Comment by ssokolow** [comment]
Ok. I've added the API docs link to `README.rst` (it turns out I actually had that exact change sitting there as an unstaged commit ever since that time crunch back in 2014).

Also, I created a PyPI account and my username is "ssokolow".

**Comment by ssokolow** [comment]
Sorry for not responding. I was waiting for some sort of "a package's ownership has been transferred to you" message that PyPI apparently doesn't send. I'll look over the PyPI entry and make any adjustments some time within the next week.
